.\" 	@(#)	[MB] cr_hl.1	Version 1.15 du 15/10/11 - 
.TH "HL" "1" "September 2015" "" "User Commands"
.SH "NAME" 
hl - Colorize strings matching regular expressions
.SH "SYNOPSIS" 
.PP 
\fBhl\fP \fB [-h|-H|-V|-[eiuvdDEL1234][-[[%.]rgybmcwRGYBMCWn] regexp ...][--config_name ...] ]\fP

or :

\fBhl\fP \fBregexp\fP

with environment variable HL_DEFAULT initialized

.SH "DESCRIPTION" 
.PP 
\fBhl\fP 
reads standard input and colorize strings matching regular expressions with specified colors.
.SH "OPTIONS" 
.IP "\fB-h\fP         " 10 
display help message
.IP "\fB-H\fP         " 10 
display help message and configuration names found in $HOME/.hl.cfg
.IP "\fB-V\fP " 10
display version information and exit
.IP "\fB-v\fP " 10
verbose
.IP "\fB-u\fP " 10
does not bufferize output on stdout
.IP "\fB-e\fP " 10
use extended regular expressions
.IP "\fB-i\fP " 10
ignore case
.IP "\fB-E\fP " 10
display on stderr every string matching the regular expression
specified by the next command line color specifier
.IP "\fB-r\fP " 10
display strings matching the associated regular expression in red
.IP "\fB-g\fP " 10
display strings matching the associated regular expression in green
.IP "\fB-y\fP " 10
display strings matching the associated regular expression in yellow
.IP "\fB-b\fP " 10
display strings matching the associated regular expression in blue
.IP "\fB-m\fP " 10
display strings matching the associated regular expression in magenta
.IP "\fB-c\fP " 10
display strings matching the associated regular expression in cyan
.IP "\fB-w\fP " 10
display strings matching the associated regular expression in white
.IP "\fB-R\fP " 10
display strings matching the associated regular expression in red
(reverse video)
.IP "\fB-G\fP " 10
display strings matching the associated regular expression in green
(reverse video)
.IP "\fB-Y\fP " 10
display strings matching the associated regular expression in yellow
(reverse video)
.IP "\fB-B\fP " 10
display strings matching the associated regular expression in blue
(reverse video)
.IP "\fB-M\fP " 10
display strings matching the associated regular expression in magenta
(reverse video)
.IP "\fB-C\fP " 10
display strings matching the associated regular expression in cyan
(reverse video)
.IP "\fB-W\fP " 10
display strings matching the associated regular expression in white
(reverse video)
.IP "\fB-n\fP " 10
display strings matching the associated regular expression uncolorized
.IP "\fB-d\fP " 10
activate debug
.IP "\fB-D\fP " 10
display specified regular expressions
.IP "\fB-L\fP " 10
lex debug
.IP "\fB-1\fP " 10
color brightness (half bright).
Changes the brightness of all the following colors, until another brightness is specified.
.IP "\fB-2\fP " 10
color brightness (normal : default).
Changes the brightness of all the following colors, until another brightness is specified.
.IP "\fB-3\fP " 10
color brightness (bright).
Changes the brightness of all the following colors, until another brightness is specified.
.IP "\fB-4\fP " 10
color brightness (underscore).
Changes the brightness of all the following colors, until another brightness is specified.
.IP "\fB-%c\fP " 10
Specifies the beginning of a range colorized in color 'c'.
.IP "\fB-.\fP " 10
Specifies the end of the range colorized in color 'c'.

.SH "PRIORITIES"
A color specifier always has a higher priority than the one that follows.
As an example, the following command :

.B	echo "abababab" | hl -r 'a' -g 'ab'

will colorize each "a" in red and each "b" in green, while the following one :

.B	echo "abababab" | hl -g 'ab' -r 'a'

will colorize each letter in green.

.SH "PARENTHESIS"
If no parenthesis are specified in the regular expression, then all characters matching the regexp will be colorized.
If parenthesis are specified, only characters captured in the parenthesis will be colorized.

.SH DEFAULT COLOR
\fBhl\fP can be used to quickly highlight strings matching a regular expression with a default color.
The environment variable HL_DEFAULT must be defined and initialized with a valid color specifier,
such as "g", "2r" or "3Y".

.SH "EXAMPLES"
.TP
Example 1 :
.B	hl -ei -c '([0-9a-f]{2}:){5}[0-9a-f]{2}'

This command colorizes a MAC address in cyan.

.TP
Example 2 :
.B	hl -e -g '\<(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\>' -r '[0-9]'

This command colorizes a valid IP address in green and an invalid IP address in red, so
that the following command :

.B	hl -e -g '\<(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\>' -r '[0-9]' <<-EOF
.nf
	192.168.266.1
	192.168.26.1
EOF
.fi
will display 192.168.266.1 in red and 192.168.26.1 in green.

.TP
Example 3 :
.B	dpkg -l | hl -ei -Er '.*systemd\>.*' -Eg '(.*(sysvinit|system-v-).*)' > /dev/null

On Debian, this command will list the packages whose description line contains strings containing the word "systemd" in red,
and lines containing "sysvinit" or "system-v-" in green, whatever the case.

.TP
Example 4 :
.B	/sbin/ifconfig -a | hl --ifconfig

Colorize the output of the ifconfig command according to the configuration \fBifconfig\fP specified in the configuration file.

.TP
Example 5 :
.B	df -h | hl --df

Colorize the output of the df command according to the configuration \fBdf\fP specified in the configuration file.

.TP
Example 6 :
.B	/sbin/ifconfig -a | hl --IP --MAC --eth

Colorize the output of the ifconfig command according to the configurations \fBIP\fP, \fBMAC\fP and \fBeth\fP specified in the configuration file.

.TP
Example 7 :
.B	cal 2015 | hl -%3c 'January' -. '^$'

Colorize the output of the \fBcal\fP command with the first three month in bright cyan : from the word \fBJanuary\fP to the first \fBempty line\fP.

.TP
Example 8 :
.B	export HL_DEFAULT=3Y; ls -l / | hl lib

Specify that the default highlight color is '3Y' (high intensity yellow in reverse video), so that hl can be used with
no color option but just one regular expression on the command line.

.SH "FILES"
.TP
Since version 1.57, the default configuration for \fBhl\fP is \fB/etc/default/hl\fP . This configuration file is common to all users.
But each user can define his own configurations in his own \fB$HOME/.hl.cfg\fP configuration file.
Users' configurations have the precedence over default configurations.

Their recognized syntax is :

- comment lines (beginning with a '#'),

- configuration definition (a name, eventually followed by spaces or tabs, and a ':'),

- configuration options for this configuration (a tab, followed by the options)

- an empty line acts as a separator between configurations

.TP
Example :

.EX
#
#	Example of .hl.cfg configuration file
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#

cal		:
	-e
	-g '[1-9][0-9][0-9][0-9]'
	-y 'January|February|March|April|May|June|July|August|September|October|November|December'
	-c 'Su|Mo|Tu|We|Th|Fr|Sa'
	-b '[0-9]'

df		:
	-e
	-r '\<((100|9[5-9])%.*)'	
	-y '\<((8[0-9]|9[0-4])%.*)'
	-c '\<[0-4][0-9]?%.*'
	-g '\<[0-9]+%.*'
	-b '^Filesystem.*'

diff		:
	-e
	-y '^<.*'
	-g '^>.*'
	-c '^([0-9]+(,[0-9]+)?[a-z][0-9]+(,[0-9]+)?)'

hl		:
	-ei
	-2B '^hl: version.*'
	-1g 'Usage'
	-2
	-R  ' +(.*\<red\>....).*reverse video.*'
	-G  ' +(.*\<green\>..).*reverse video.*'
	-Y  ' +(.*\<yellow\>.).*reverse video.*'
	-B  ' +(.*\<blue\>...).*reverse video.*'
	-M  ' +(.*\<magenta\>).*reverse video.*'
	-C  ' +(.*\<cyan\>...).*reverse video.*'
	-W  ' +(.*\<white\>..).*reverse video.*'
	-w  '(\(reverse video\))'
	-r  '.*\<red\>.*'
	-g  '.*\<green\>.*'
	-y  '.*\<yellow\>.*'
	-b  '.*\<blue\>.*'
	-m  '.*\<magenta\>.*'
	-c  '.*\<cyan\>.*'
	-w  '.*\<white\>.*'
.EE

.SH "SEE ALSO"
hl(5)

.SH "MAN PAGE VERSION"
The version of this man page is 1.15.
It is compatible with hl version 1.63 and upper.

.SH "AUTHOR" 
.PP 
The original version of this manual page was written by Martial Bornet
<mbornet (.) pro (at) wanadoo (.) fr> for the \fBGNU/Linux\fP  system.

The author also can be contacted with <man (.) flashnux (at) gmail (.) com>.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU GPL.
