#!/bin/bash
#
#	Colorize the output of the diff command
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] cr_hl_diff	Version 1.2 du 15/04/07 - 
#

hl -e -y '^<.*' -g '^>.*' -c '^[0-9]+(,[0-9]+)?[a-z][0-9]+(,[0-9]+)?'
