#!/bin/bash
#
#    Colorize iptables rules
#    ~~~~~~~~~~~~~~~~~~~~~~~
#
#    @(#)  [MB] cr_hl_iptables Version 1.1 du 15/03/22 - 
#


hl -e     -c 'INPUT'                         \
          -y 'FORWARD|POSTROUTING'           \
          -b '#.*'                           \
          -W 'OUTPUT'                        \
          -g '.*ACCEPT.*'                    \
          -r '.*(DROP|REJECT).*'             \
          -m 'iptables.*-F.*'                \
          -w '^iptables .*'
