#!/bin/bash

<<-EOF ./hl -r 'red' -g 'green' -y 'yellow' -b 'blue' -m 'magenta' -c 'cyan' -w 'white' -R 'RED' -G 'GREEN' -Y 'YELLOW' -B 'BLUE' -M 'MAGENTA' -C 'CYAN' -W 'WHITE'
	  ./hl -r 'red' -g 'green' -y 'yellow' -b 'blue' -m 'magenta' -c 'cyan' -w 'white' -R 'RED' -G 'GREEN' -Y 'YELLOW' -B 'BLUE' -M 'MAGENTA' -C 'CYAN' -W 'WHITE'
EOF
 
<<-EOF ./hl -r 'A' -g 'B' -y 'C' -b 'D' -m 'E' -c 'F' -w 'G' -R 'H' -G 'I' -Y 'J' -B 'K' -M 'L' -C 'M' -W 'N'
	ABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZ
EOF

<<-EOF ./hl -e -r '^A[^F]*E' -g 'B|Z$' -y 'C' -b 'D' -m 'E' -c 'F' -w 'G' -R 'H' -G 'T[^S]*Z$' -Y 'J' -B 'K' -M 'L' -C 'M' -W 'N'
	ABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZABCDEFGHIJKMNOPQRSTUVWXYZ
EOF
