#!/bin/bash
#
#	Script for command output colorization
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] cr_hl_generic	Version 1.13 du 16/12/23 - 
#
#	This script calls the original programme with all the arguments
#	it received, and  pipes it to "hl" using its name as the "hl"
#	configuration.
#
#	In case the user doesn't want the output of the command to
#	be colorized, the following syntax must be used :
#	USE_HL=no cmd [args ...]
#

OUT=/tmp/OUT.$$
ERR=/tmp/ERR.$$

mknod $OUT p
mknod $ERR p

case "$USE_HL" in
	n|N|no|NO|0)	USE_HL="no"
				;;
esac

progname="$(basename $0)"
pathname="$(type -p "$progname")"
dirname="$(dirname "$pathname")"

PATH="$(echo "$PATH" | sed "s|^$dirname:||;s|:$dirname:|:|g")"
export PATH

if [ "$WHICH" = 1 ]; then
	type "$progname"
	exit 1
fi

if [ "$USE_HL" = "no" ]; then
	# No colorization
	# ~~~~~~~~~~~~~~~
	"$progname" "$@"
	rc=$?
else
	# Default behaviour : colorization
	# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	hl -u --"$progname" < "$ERR" >&2 & hl --"$progname" < "$OUT" & \
		"$progname" "$@" > "$OUT" 2> "$ERR"

	rc=$?

fi

wait

rm -f "$OUT" "$ERR"

exit $rc
