#!/bin/bash
#
#	Colorize the output of the df command
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] cr_hl_df	Version 1.2 du 15/04/29 - 
#

#df -P | hl -e -r '\<(100|9[5-9])%' -y '\<(8[0-9]|9[0-4])%' -g '\<[0-9]+%' -b '^Filesystem.*'
hl -e -r '\<(100|9[5-9])%.*' -y '\<(8[0-9]|9[0-4])%.*' -c '\<[0-4][0-9]?%.*' -g '\<[0-9]+%.*' -b '^Filesystem.*'
