#!/bin/bash
#
#	@(#)	[MB] cr_hl_hl	Version 1.1 du 15/06/08 - 
#

./hl -i	\
	-R '.*\<red\>.*reverse video.*'		\
	-G '.*\<green\>.*reverse video.*'		\
	-Y '.*\<yellow\>.*reverse video.*'		\
	-B '.*\<blue\>.*reverse video.*'		\
	-M '.*\<magenta\>.*reverse video.*'	\
	-C '.*\<cyan\>.*reverse video.*'		\
	-W '.*\<white\>.*reverse video.*'		\
	-r '.*\<red\>.*'					\
	-g '.*\<green\>.*'					\
	-y '.*\<yellow\>.*'					\
	-b '.*\<blue\>.*'					\
	-m '.*\<magenta\>.*'				\
	-c '.*\<cyan\>.*'					\
	-w '.*\<white\>.*'					
