#!/bin/bash
#
#	Script for the highlighting of the "ifconfig" command
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#
#


hl -ei	-m '^(eth|(vir)?br|vnet)[0-9.]*:[0-9]+\>'		\
	-b '^(eth|(vir)?br|vnet)[0-9.]*\.[0-9]+\>'		\
	-c '([0-9a-f]{2}:){5}[0-9a-f]{2}'			\
	-g '\<UP\>|\<RUNNING\>|([0-9]{1,3}\.){3}[0-9]{1,3}\>'	\
	-y '^(eth|(vir)?br|vnet)[0-9.:]*\>'

