#!/bin/bash
#
#	Colorize the output of the xxd command
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] cr_hl_xxd	Version 1.1 du 15/05/03 - 
#

hl -e -r '(\<0a)|(0a\>)' -b '^[^:]+' -g '.{16}$' -c '[[:xdigit:]]'
