#!/bin/bash
#
#	Display differences between the definition of an hl configuration
#	in two specified configurations files
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] 	Version 1.1 du 21/05/29 - 
#

usage()
{
	cat <<- EOF
		Usage: $PROGNAME config_name config_path1 config_path2
	EOF
}

PROGNAME=`basename "$0"`

if [ "$3" = '' -o "$4" != '' ]; then
	usage
	exit 1
fi

config_name="$1"
config_path1="$2"
config_path2="$3"

diff <(HL_CONF="$config_path1" hl -v -oP "\<$config_name\>") <(HL_CONF="$config_path2" hl -v -oP "\<$config_name\>") 
