#!/bin/bash
#
#	Compute MD5 checksums of configurations whose name is specified
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] 	Version 1.1 du 21/05/29 - 
#

export HL_A2='3c'

cfg="$1"
(
	for file in $(hl -oP "\<$cfg\>" | awk '{ print $1}' | sort -u)
	do
		# echo "$file" > /dev/tty
		# args HL_CONF='/DATA3/projets/hl/config_files/hl_HW.cfg' hl -v -oP "\<$cfg\>" > /dev/tty
		# HL_CONF="$file" hl -v -oP "\<$cfg\>" > /dev/tty

		MD5=$(HL_CONF="$file" hl -v -oP "\<$cfg\>" | sed '1d' | md5sum)
		printf "%s  %s\n" "$MD5" "$file"
	done
) | sort -k1,1 | hl --dupA1
