#!/bin/bash
#
# Copyright (C) 2017-2019, Martial Bornet
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#	@(#)	[MB] aj_ls_by_day	Version 1.3 du 20/07/03 - 
#

hl_opts()
{
	for d in {0..9}
	do
		case $d in
			0)	color=3w
				;;

			1)	color=3m
				;;

			2)	color=3r
				;;

			3)	color=2y
				;;

			4)	color=3y
				;;

			5)	color=3g
				;;

			6)	color=2g
				;;

			7)	color=3c
				;;

			8)	color=3b
				;;

			9)	color=2b
				;;

			*)	color=n
				;;
		esac

		HL_COL="-$color"
		day=$(date '+%b %2e' -d "@$(echo "$(date '+%s') 24 3600 * $d * - p" | dc)")
		HL_RE="$day ..:.. .+"
		echo -n "$HL_COL" "'$HL_RE' "
	done

	 echo " "

}

/bin/ls -l "$@" | eval hl -e "$(hl_opts)"
