#!/bin/bash
#
# Copyright (C) 2017-2019, Martial Bornet
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#	@(#)	[MB] ek_lY	Version 1.2 du 22/09/06 - 
#

if [ "$HL" = '' ]; then
	export HL='hl'
fi

# export HL_TIME_REGEX_Y='(([0-9]{4}).*)'
export HL_TIME_REGEX_Y='(([0-9]{4})-([0-9]{2})-([0-9]{2}).*)'
export HL_TIME_REGEX_m='(([0-9]{4})-([0-9]{2}).*)'
export HL_TIME_REGEX_d='(([0-9]{4})-([0-9]{2})-([0-9]{2}).*)'
export HL_TIME_REGEX_H='(([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}).*)'
export HL_TIME_REGEX_M='(([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}).*)'
export HL_TIME_REGEX_S='(([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2}).*)'
export HL_TIME_REGEX_u='(([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2})\.([0-9]{6}).*)'
export HL_TIME_REGEX_n='(([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2})\.([0-9]{9}).*)'

FMT_Y='+%Y-%m-%d'
FMT_W='+%Y-%m-%d'
FMT_d='+%Y-%m-%d'
FMT_M='+%Y-%m-%d %H:%M'
FMT_S='+%Y-%m-%d %H:%M:%S'

name=$(basename "$0")

case "$name" in
	lY)		FMT="$FMT_Y"
			T_OPT='-tY'
			;;

	lm)		FMT="$FMT_d"
			T_OPT='-tm'
			;;

	lW)		FMT="$FMT_W"
			T_OPT='-tw'
			;;

	lD)		FMT="$FMT_d"
			T_OPT='-td'
			;;
	lH)		FMT="$FMT_M"
			T_OPT='-tH'
			;;

	lM)		FMT="$FMT_M"
			T_OPT='-tM'
			;;
	lS)		FMT="$FMT_S"
			T_OPT='-tS'
			;;


	*)		echo "$name: unknown script name" >&2
			exit 1
esac


/bin/ls --time-style="$FMT" -l "$@" | "$HL" "$T_OPT"
