#!/bin/bash
#
#	Launch all tests for option -t of "hl"
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] ek_all_tests_-t	Version 1.6 du 22/09/03 - 
#

readonly REF_DATE='2000-06-23 12:34:56.123456789'

if [ "$HL" = '' ]; then
	export HL='hl'
fi

label()
{
	case "$1" in
		Y)		echo "year"
				;;

		m)		echo "month"
				;;

		w)		echo "week"
				;;

		d)		echo "day"
				;;

		H)		echo "hour"
				;;

		M)		echo "minute"
				;;

		S)		echo "second"
				;;

		u)		echo "micro-second"
				;;

		n)		echo "nano-second"
				;;

		*)		echo "unknown period"
				;;
	esac
}

for opt in Y m w d H M S u n
do
	for zero in '' '0'
	do
		echo "========== `label "$opt"` =========="
		echo "[$(date '+%Y-%m-%d %H:%M:%S')]"
		echo "./dates_gen -$opt | $HL -t${opt}${zero}"
		./dates_gen -"$opt" | "$HL" -t"${opt}${zero}"
		echo "---------- `label "$opt"` with reference date $REF_DATE ----------"
		echo "./dates_gen -$opt '$REF_DATE' | $HL -t${opt}${zero}R '$REF_DATE'"
		./dates_gen -"$opt" "$REF_DATE" | "$HL" -t"${opt}${zero}"R "$REF_DATE"
		echo
	done
done
