#!/bin/bash
#
#	Launch all tests for option -t of "hl"
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] ek_all_tests_-t	Version 1.3 du 22/08/21 - 
#

readonly REF_DATE='2000-06-23 12:34:56.123456789'

if [ "$HL" = '' ]; then
	export HL='hl'
fi

label()
{
	case "$1" in
		Y)		echo "year"
				;;

		m)		echo "month"
				;;

		w)		echo "week"
				;;

		d)		echo "day"
				;;

		H)		echo "hour"
				;;

		M)		echo "minute"
				;;

		S)		echo "second"
				;;

		u)		echo "micro-second"
				;;

		n)		echo "nano-second"
				;;

		*)		echo "unknown period"
				;;
	esac
}

for opt in Y m w d H M S u n
do
	echo "========== `label "$opt"` =========="
	./dates_gen -"$opt" | "$HL" -t"$opt"
	echo "---------- `label "$opt"` with reference date $REF_DATE ----------"
	./dates_gen -"$opt" "$REF_DATE" | "$HL" -t"$opt"R "$REF_DATE"
	echo
done
